version: '3.5'

services:
  auth_postgres:
    image: postgres:13
    networks:
      - auth_postgres
    expose:
      - ${AUTH_POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_NAME}
    volumes:
      - auth_pg_data:/var/lib/postgresql/data/
    ports:
      - 5432:${AUTH_POSTGRES_PORT}

  auth_redis:
    image: redis:latest
    expose:
      - ${AUTH_REDIS_PORT}
    networks:
      - auth_redis
    volumes:
      - auth_redis_data:/var/lib/redis/data
    ports:
      - 6379:${AUTH_REDIS_PORT}


volumes:
  auth_pg_data:
  auth_redis_data:

networks:
  auth_postgres:
    name: movies_net
  auth_redis:
    name: movies_net
